export const uiCopy = {
  appName: "Resonance",
  actions: {
    openRecorder: "Open recorder",
    openLibrary: "Open library",
    openLibraryFolder: "Open library folder",
    openDiagnostics: "Open diagnostics",
    openSetupGuide: "Open setup & settings",
    startSession: "Start session",
    stopSession: "Stop session",
    refresh: "Refresh",
    selectAllVisible: "Select all visible",
    clearSelection: "Clear selection",
    refreshHealth: "Refresh health",
    refreshDevices: "Refresh devices",
    runQuickTest: "Run quick test",
    detectWhisperRepo: "Detect whisper.cpp repo",
    detectWhisper: "Detect whisper.cpp",
    detectModel: "Detect model",
    openSummary: "Open summary",
    openTranscript: "Open transcript",
    openLiveTranscript: "Open live transcript",
    previewTranscript: "Preview raw transcript",
    previewDiagnostics: "Preview diagnostics",
    regenerateTranscript: "Generate transcript",
    regenerateSummary: "Generate summary",
    exportAudio: "Export audio",
    deleteAudio: "Delete audio",
    deleteTranscript: "Delete transcript",
    playAudio: "Play audio",
    hideAudio: "Hide audio",
    showFolder: "Show folder",
    deleteSession: "Delete session",
    close: "Close",
  },
  status: {
    ready: "Ready to record",
    blocked: "Configuration blocked",
    busy: "Session busy",
    healthy: "Healthy",
    warning: "Needs attention",
    failed: "Blocked",
  },
  dashboard: {
    blockedReason: "Resolve the blocking checks below before starting a session.",
    busyReason: "A session is already running. Stop it here when you are ready to finalize the summary.",
  },
  diagnostics: {
    title: "Diagnostics",
    subtitle: "Health checks for the local-first recording pipeline.",
    blocking: "Blocking issues",
    warnings: "Warnings",
    healthy: "Healthy checks",
    noBlocking: "No blocking issues detected.",
    noWarnings: "No warnings detected.",
    smokePassed: "Quick test completed successfully.",
  },
  library: {
    title: "Session Library",
    subtitle: "Review finished and failed sessions from manifest-backed metadata.",
    all: "All",
    done: "Done",
    failed: "Failed",
    searchPlaceholder: "Search sessions",
    empty: "No sessions match the current filters.",
    deleteConfirmation: "Delete this session and its vault notes?",
  },
  settings: {
    title: "Local recording, transcription, and summaries for Obsidian.",
  },
  notices: {
    sessionComplete: "Session completed.",
    sessionDeleted: "Session deleted.",
    sessionBusy: "Session is busy. Please wait for the current operation to finish.",
    whisperNotDetected: "whisper.cpp CLI was not auto-detected.",
    whisperDetected: "whisper.cpp CLI updated.",
    whisperRepoNotDetected: "whisper.cpp repo was not auto-detected.",
    whisperRepoDetected: "whisper.cpp repo path updated.",
    modelNotDetected: "No readable whisper model was auto-detected.",
    modelDetected: "Whisper model path updated.",
    quickTestFailedPrefix: "Quick test failed",
  },
} as const;
